name: Docker Build

on:
  push:
    branches: [ DEVOPS-262---Docker-deploy-Action ]
  pull_request:
    branches: [ develop ]

jobs:

  docker_deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Check out GitHub repo
      if: "!contains(github.event.head_commit.message, 'skip ci')"
      uses: actions/checkout@v2

    - name: Build and Push to Packages
      if: "!contains(github.event.head_commit.message, 'skip ci')"    
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: kbase/narrative/narrative-dev
        tags: ci-test
        tag_with_ref: true
        tag_with_sha: true